server:
  port: ${SERVER_PORT:8000}

spring:
  application:
    name: java-clean-arch
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dbtest}
    username: ${DB_USERNAME:dbtest}
    password: ${DB_PASSWORD:dbtest}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect