version: "3.8"

services:
  clean-arch-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dbtest
      POSTGRES_PASSWORD: dbtest
      POSTGRES_DB: dbtest
    ports:
      - "5432:5432"

  clean-arch-app:
    build:
      context: ../
      dockerfile: Dockerfile
    image: jeffersontdm/clean-arch-app
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_HOST: clean-arch-db
      DB_PORT: 5432
      DB_NAME: dbtest
      DB_USERNAME: dbtest
      DB_PASSWORD: dbtest
    depends_on:
      - clean-arch-db